name: Deploy and Build Develop Branch
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@develop
      - name: Install Dependencies
        run: yarn
      - name: Create .env file
        run: |
          echo "REACT_APP_MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com" >> $GITHUB_ENV
          echo "REACT_APP_NETWORK_TYPE=testnet" >> $GITHUB_ENV
      - name: Build
        run: CI=false yarn build # CI=false should be removed for prod
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Create firebase.json
        run: |
          echo '${{ secrets.FIREBASE_TESTNET_CONFIG }}' > firebase.json
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_TESTNET }}
